import Foundation
import UsageMeterCore

/// The command's published shape. Consumers depend on these names, so
/// treat a change to any of them as a schema version bump. The same
/// goes for key presence: `Account`, `Window`, and `Balance` each
/// write their own `encode(to:)` so a nil field publishes as `null`
/// instead of vanishing, because a fixed schema needs every key to
/// exist whether or not the data does. Keep those `encode(to:)`
/// methods rather than trimming them back to synthesis.
///
/// The golden fixture this type is tested against
/// (`Tests/UsageMeterCLITests/Fixtures/usage-report-v1.json`) is
/// generated by the real encoder, not hand-typed, and must stay that
/// way: regenerate it with a throwaway encode-and-save test rather
/// than editing its JSON by hand. A value like
/// `0.21999999999999997` is the true `Double` behind `1 - 0.78`, not
/// a typo — rounding it to `0.22` would freeze a different number
/// than the one this code actually computes.
struct UsageReportDocument: Codable, Equatable {
  static let currentSchemaVersion = 1

  let schemaVersion: Int
  let generatedAt: Date
  let accounts: [Account]

  init(report: UsageReport, generatedAt: Date) {
    schemaVersion = Self.currentSchemaVersion
    self.generatedAt = generatedAt
    accounts = report.accounts.map(Account.init)
  }

  static func encoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    encoder.dateEncodingStrategy = .iso8601
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    return encoder
  }

  struct Account: Codable, Equatable {
    let id: UUID
    let provider: String
    let providerDisplayName: String
    let displayName: String
    let identity: String?
    let fetchedAt: Date?
    let windows: [Window]
    let balances: [Balance]

    init(account: UsageReportAccount) {
      id = account.accountID
      provider = account.provider.rawValue
      providerDisplayName = account.providerDisplayName
      displayName = account.displayName
      identity = account.identity
      fetchedAt = account.fetchedAt
      windows = account.windows.map(Window.init)
      balances = account.balances.map(Balance.init)
    }

    // `encode`, not the synthesized `encodeIfPresent`: a nil identity
    // or fetch time publishes as `null`, not a missing key.
    func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(id, forKey: .id)
      try container.encode(provider, forKey: .provider)
      try container.encode(providerDisplayName, forKey: .providerDisplayName)
      try container.encode(displayName, forKey: .displayName)
      try container.encode(identity, forKey: .identity)
      try container.encode(fetchedAt, forKey: .fetchedAt)
      try container.encode(windows, forKey: .windows)
      try container.encode(balances, forKey: .balances)
    }
  }

  struct Window: Codable, Equatable {
    let id: String
    let kind: String
    let label: String?
    let durationSeconds: Int
    let consumedPercent: Int
    let remainingFraction: Double
    let resetAt: Date?

    init(window: UsageWindow) {
      id = window.id
      kind = window.kind.rawValue
      label = window.label
      durationSeconds = Int(window.duration.rounded())
      consumedPercent = window.consumedPercent
      remainingFraction = window.remainingFraction
      resetAt = window.resetAt
    }

    // `encode`, not `encodeIfPresent`: a nil label or reset time
    // publishes as `null` rather than disappearing.
    func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(id, forKey: .id)
      try container.encode(kind, forKey: .kind)
      try container.encode(label, forKey: .label)
      try container.encode(durationSeconds, forKey: .durationSeconds)
      try container.encode(consumedPercent, forKey: .consumedPercent)
      try container.encode(remainingFraction, forKey: .remainingFraction)
      try container.encode(resetAt, forKey: .resetAt)
    }
  }

  struct Balance: Codable, Equatable {
    let id: String
    let label: String
    let state: String
    let remainingAmount: Double?
    let unit: String?
    let cycleEndsAt: Date?

    init(balance: UsageBalance) {
      id = balance.id
      label = balance.label
      cycleEndsAt = balance.cycleEndsAt
      // Both return nil unless the value is .available.
      remainingAmount = balance.remainingAmount
      unit = balance.unit
      state =
        switch balance.value {
        case .available: "available"
        case .unlimited: "unlimited"
        case .disabled: "disabled"
        }
    }

    // `encode`, not `encodeIfPresent`: an unlimited or disabled
    // balance still publishes `remainingAmount`, `unit`, and
    // `cycleEndsAt` as `null` rather than omitting them.
    func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(id, forKey: .id)
      try container.encode(label, forKey: .label)
      try container.encode(state, forKey: .state)
      try container.encode(remainingAmount, forKey: .remainingAmount)
      try container.encode(unit, forKey: .unit)
      try container.encode(cycleEndsAt, forKey: .cycleEndsAt)
    }
  }
}
